//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microservices.Commands.Domain.Base.ValueObjects.General {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DomainGeneralValueObjectsNotificationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DomainGeneralValueObjectsNotificationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microservices.Commands.Domain.Base.ValueObjects.General.DomainGeneralValueObjects" +
                            "NotificationMessages", typeof(DomainGeneralValueObjectsNotificationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cidade deve ser informada..
        /// </summary>
        internal static string Address_City_Empty {
            get {
                return ResourceManager.GetString("Address_City_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O complemento do endereço deve ter até {0} caracteres..
        /// </summary>
        internal static string Address_Complement_MaxLengthOverflow {
            get {
                return ResourceManager.GetString("Address_Complement_MaxLengthOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O bairro deve ser informado..
        /// </summary>
        internal static string Address_Neighborhood_Empty {
            get {
                return ResourceManager.GetString("Address_Neighborhood_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O bairro deve ter até {0} caracteres..
        /// </summary>
        internal static string Address_Neighborhood_MaxLengthOverflow {
            get {
                return ResourceManager.GetString("Address_Neighborhood_MaxLengthOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O logradouro deve ser informado..
        /// </summary>
        internal static string Address_Street_Empty {
            get {
                return ResourceManager.GetString("Address_Street_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CEP deve ser informado..
        /// </summary>
        internal static string Address_ZipCode_Empty {
            get {
                return ResourceManager.GetString("Address_ZipCode_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O identificador da cidade é inválido..
        /// </summary>
        internal static string City_Id_Invalid {
            get {
                return ResourceManager.GetString("City_Id_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome da cidade deve ser informado..
        /// </summary>
        internal static string City_Name_Empty {
            get {
                return ResourceManager.GetString("City_Name_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome da cidade deve ter até {0} caracteres..
        /// </summary>
        internal static string City_Name_MaxLengthOverflow {
            get {
                return ResourceManager.GetString("City_Name_MaxLengthOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O estado da cidade deve ser informado..
        /// </summary>
        internal static string City_State_Empty {
            get {
                return ResourceManager.GetString("City_State_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O identificador do estado é inválido..
        /// </summary>
        internal static string State_Id_Invalid {
            get {
                return ResourceManager.GetString("State_Id_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do estadodeve ser informado..
        /// </summary>
        internal static string State_Name_Empty {
            get {
                return ResourceManager.GetString("State_Name_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do estado deve ter até {0} caracteres..
        /// </summary>
        internal static string State_Name_MaxLengthOverflow {
            get {
                return ResourceManager.GetString("State_Name_MaxLengthOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CEP informado é inválido..
        /// </summary>
        internal static string ZipCode_Code_Invalid {
            get {
                return ResourceManager.GetString("ZipCode_Code_Invalid", resourceCulture);
            }
        }
    }
}
